"""Regression tests for the generated validate_bounds composition.

validate_bounds is generated by likelihood._validate_bounds_function from
the instance's own check_bounds/correct_bounds pair, so the three bounds
behaviors cannot diverge for non-rectangular geometries, and the second
check runs on the array correct_bounds returns — a correct_bounds is free
to be pure (fresh output array, input untouched) rather than mutating its
input in place.
"""

from typing import NamedTuple, override

import numpy as np
from numba import njit
from numpy.typing import NDArray

from DTMCMC.likelihood import RectangularLikelihood
from DTMCMC.rng_helpers import get_rng

# corrected points land strictly inside the disk so the recheck of the
# projected point cannot flip on float rounding of radius / norm
_PROJECTION_SAFETY = 0.999


class _DiskInputs(NamedTuple):
    n_par: int
    low_lims: NDArray[np.floating]
    high_lims: NDArray[np.floating]
    radius: float


@njit(inline='always')
def _disk_loglike(_params: NDArray[np.floating], _inputs: _DiskInputs) -> float:
    return 0.0


@njit(inline='always')
def _disk_check_bounds(v: NDArray[np.floating], inputs: _DiskInputs) -> bool:
    """Non-rectangular support: the disk inscribed in the rectangular box."""
    return float(np.sum(v * v)) <= inputs.radius**2


@njit(inline='always')
def _disk_correct_bounds(v: NDArray[np.floating], inputs: _DiskInputs) -> NDArray[np.floating]:
    """Radial projection onto the disk; pure — never mutates its input."""
    norm = float(np.sqrt(np.sum(v * v)))
    if norm <= inputs.radius:
        return v.copy()
    return v * (_PROJECTION_SAFETY * inputs.radius / norm)


@njit(inline='always')
def _identity_correct_bounds(v: NDArray[np.floating], inputs: _DiskInputs) -> NDArray[np.floating]:  # noqa: ARG001
    """A correction that never fixes anything (pure identity copy)."""
    return v.copy()


class _DiskLikelihood(RectangularLikelihood[_DiskInputs]):
    """Likelihood whose bounds behaviors are a custom non-rectangular pair."""

    def __init__(self, radius: float = 1.0) -> None:
        n_par = 2
        low_lims = np.full(n_par, -2.0)
        low_lims.setflags(write=False)
        high_lims = np.full(n_par, 2.0)
        high_lims.setflags(write=False)
        self._inputs_disk = _DiskInputs(n_par, low_lims, high_lims, radius)
        super().__init__(n_par, low_lims, high_lims)

    @property
    @override
    def inputs(self) -> _DiskInputs:
        return self._inputs_disk

    @property
    @override
    def loglike_fn(self):
        return _disk_loglike

    @property
    @override
    def check_bounds_fn(self):
        return _disk_check_bounds

    @property
    @override
    def correct_bounds_fn(self):
        return _disk_correct_bounds


class _UncorrectableDiskLikelihood(_DiskLikelihood):
    """Disk check paired with a correction that cannot restore validity."""

    @property
    @override
    def correct_bounds_fn(self):
        return _identity_correct_bounds


def test_validate_bounds_composes_custom_nonrectangular_pair() -> None:
    """The generated validate_bounds runs the instance's own check/correct pair.

    The probe point sits inside the rectangular box but outside the disk,
    so any rectangular hard-coding would pass it through unchanged; the
    generated composition must instead detect it via the custom check and
    return the custom radial correction.
    """
    like = _DiskLikelihood(radius=1.0)

    inside = np.array([0.3, -0.4])
    point, success = like.validate_bounds(inside.copy())
    assert success
    np.testing.assert_array_equal(point, inside)

    outside = np.array([1.5, 0.0])
    corrected, success = like.validate_bounds(outside.copy())
    assert success
    np.testing.assert_allclose(corrected, np.array([_PROJECTION_SAFETY, 0.0]))
    assert like.check_bounds(corrected)

    # the unbaked native handle composes identically
    corrected_native, success_native = like.validate_bounds_fn(outside.copy(), like.inputs)
    assert success_native
    np.testing.assert_allclose(corrected_native, corrected)


def test_validate_bounds_success_rechecks_the_returned_point() -> None:
    """The success flag comes from re-checking what correct_bounds returned."""
    like = _UncorrectableDiskLikelihood(radius=1.0)
    outside = np.array([1.5, 0.0])
    returned, success = like.validate_bounds(outside.copy())
    assert not success
    np.testing.assert_array_equal(returned, outside)


def test_validate_bounds_does_not_rely_on_inplace_correction() -> None:
    """A pure correct_bounds (fresh output array) still validates correctly.

    The corrected point must be the array correct_bounds returned, with the
    recheck applied to it — the input array is not consulted again and
    stays untouched.
    """
    like = _DiskLikelihood(radius=1.0)
    outside = np.array([0.0, -1.8])
    original = outside.copy()
    corrected, success = like.validate_bounds(outside)
    assert success
    np.testing.assert_array_equal(outside, original)
    np.testing.assert_allclose(corrected, np.array([0.0, -_PROJECTION_SAFETY]))


def test_validate_bounds_matches_manual_composition() -> None:
    """validate_bounds equals check -> correct -> re-check over probe points."""
    like = _DiskLikelihood(radius=1.0)
    rng = get_rng(20260728)
    for _ in range(64):
        probe = rng.uniform(-2.0, 2.0, size=2)
        got_point, got_success = like.validate_bounds(probe.copy())
        if like.check_bounds(probe):
            assert got_success
            np.testing.assert_array_equal(got_point, probe)
        else:
            expected = like.correct_bounds(probe.copy())
            np.testing.assert_array_equal(got_point, expected)
            assert got_success == like.check_bounds(expected)
